;INCLUDE "constants.asm"

;SECTION "data/types/search_strings.asm", ROMX

PokedexTypeSearchStrings::
	db "NORMAL  @" ; NORMAL
	db "FIRE    @" ; FIRE
	db "WATER   @" ; WATER
	db "GRASS   @" ; GRASS
	db "ELECTRIC@" ; ELECTRIC
	db "ICE     @" ; ICE
	db "FIGHTING@" ; FIGHTING
	db "POISON  @" ; POISON
	db "GROUND  @" ; GROUND
	db "FLYING  @" ; FLYING
	db "PSYCHIC @" ; PSYCHIC
	db "BUG     @" ; BUG
	db "ROCK    @" ; ROCK
	db "GHOST   @" ; GHOST
	db "DRAGON  @" ; DRAGON
