if DEF(UNFINISHED_BROKEN_DONT_ENABLE)
Functionfdb66:
	ld   a,$01
	ld   ($ff00+hInMenu),a
	ld   a,$80
	ld   (wBadges),a
	ld   hl,wNumBagItems
	ld   de,DebugFightFunc5C29
DebugFightFunc5B75:
	ld   a,(de)
	cp   a,$FF
	jr   z,DebugFightFunc5B8A
	inc  de
	ld   (wCurItem),a
	ld   a,(de)
	inc  de
	ld   (wItemQuantity),a
	push de
	call ReceiveItem
	pop  de
	jr   DebugFightFunc5B75:
DebugFightFunc5B8A:
	call LoadFontsBattleExtra
	call ClearTileMap
	call ClearSprites
	ld   hl,wShadowOAMEnd
	ld   b,$01
	ld   c,$12
	call DrawTextBox
	ld   hl,w_C2BA
	ld   de,DebugFightFunc6169
	call PlaceString
	ld   hl,w_C2F4
	ld   de,DebugFightFunc6172
	call PlaceString
	ld   hl,w_C319
	ld   de,DebugFightFunc6181
	call PlaceString
	xor  a
	ld   (wCurPartyMon),a
	ld   (wEnemyMon),a
	ld   (wEnemyMonLevel),a
	ld   (wBattleMonStructEnd),a
	ld   (w_D900),a
	ld   b,a
	ld   c,a
	ld   hl,wOTPartySpecies
	call DebugFightFunc5C20
	ld   hl,wPartyCount
	call DebugFightFunc5C20
	ld   de,wPartySpecies
	ld   hl,w_C31C
DebugFightFunc5BDC:
	push hl
	push bc
	dec  hl
	ld   a,ED
	ld   (hl),a
	ld   bc,$000B
	add  hl,bc
	ld   a,7F
	ld   (hl),a
	push de
	pop  de
	pop  bc
	pop  hl
DebugFightFunc5BED:
	push bc
	push de
	call DelayFrame
	call GetJoypadDebounced
	pop  de
	pop  bc
	ld   a,($ff00+hJoySum)
	bit  0,a
	jp   nz,DebugFightFunc5C36
	bit  1,a
	jp   nz,DebugFightFunc5C75
	bit  3,a
	jp   nz,DebugFightFunc5DA7
	bit  4,a
	jp   nz,DebugFightFunc5CC6
	bit  6,a
	jp   nz,DebugFightFunc5C82
	bit  7,a
	jp   nz,DebugFightFunc5CA5
	bit  2,a
	ld   a,04
	jp   nz,Predef
	jr   DebugFightFunc5BED
DebugFightFunc5C20:
	xor  a
	ldi  (hl),a
	ldi  (hl),a
	ldi  (hl),a
	ldi  (hl),a
	ldi  (hl),a
	ldi  (hl),a
	ld   (hl),a
	ret
DebugFightFunc5C29:
	ld   bc,$0263
	ld   h,e
	inc  b
	ld   h,e
	dec  b
	ld   h,e
	ld   c,63
	jr   z,DebugFightFunc5C98
	rst  38
DebugFightFunc5C36:
	inc  b
	ld   a,b
	cp   a,$FE
	jr   c,DebugFightFunc5C3E
	xor  a
	ld   b,a
DebugFightFunc5C3E:
	ld   (de),a
	ld   (wNamedObjectIndexBuffer),a
	push bc
	push hl
	push de
	ld   bc,$8103
	call PrintNumber
	inc  hl
	push hl
	ld   de,DebugFightFunc61ED
	call PlaceString
	ld   bc,hFFEC
	add  hl,bc
	ld   de,DebugFightFunc61ED
	call PlaceString
	pop  hl
	ld   a,(wNamedObjectIndexBuffer)
	and  a
	jr   nz,DebugFightFunc5C69
	ld   de,DebugFightFunc61F3
	jr   DebugFightFunc5C6C
DebugFightFunc5C69:
	call GetPokemonName
DebugFightFunc5C6C:
	call PlaceString
	pop  de
	pop  hl
	pop  bc
	jp   DebugFightFunc5BED
DebugFightFunc5C75:
	dec  b
	ld   a,b
	cp   a,$FE
	jp   c,DebugFightFunc5C3E
	ld   a,$FD
	ld   b,a
	jp   DebugFightFunc5C3E
DebugFightFunc5C82:
	ld   a,(wCurPartyMon)
	dec  a
	cp   a,$FF
	jp   z,DebugFightFunc5BED
	ld   (wCurPartyMon),a
	dec  de
	dec  hl
	ld   a,$7F
	ld   (hl),a
	push bc
	ld   bc,hSerialReceive
	add  hl,bc
DebugFightFunc5C98:
	pop  bc
	ld   a,$ED
	ld   (hl),a
	inc  hl
	push hl
	call DebugFightFunc5D8C
	pop  hl
	jp   DebugFightFunc5BED
DebugFightFunc5CA5:
	ld   a,(wCurPartyMon)
	inc  a
	cp   a,$06
	jp   nc,DebugFightFunc5BED
	ld   (wCurPartyMon),a
	inc  de
	dec  hl
	ld   a,$7F
	ld   (hl),a
	ld   bc,$0028
	add  hl,bc
	ld   a,$ED
	ld   (hl),a
	inc  hl
	push hl
	call DebugFightFunc5D8C
	pop  hl
	jp   DebugFightFunc5BED
DebugFightFunc5CC6:
	push hl
	push bc
	dec  hl
	ld   a,$7F
	ld   (hl),a
	ld   bc,$000B
	add  hl,bc
	ld   a,$ED
	ld   (hl),a
	pop  bc
	pop  hl
DebugFightFunc5CD5:
	push bc
 	push de
 	call DelayFrame
 	call GetJoypadDebounced
 	pop  de
 	pop  bc
 	ld   a,($ff00+hJoySum)
 	bit  0,a
 	jp   nz,DebugFightFunc5D01
 	bit  1,a
 	jp   nz,DebugFightFunc5D2A
 	bit  3,a
 	jp   nz,DebugFightFunc5DA7
 	bit  5,a
 	jp   nz,DebugFightFunc5BDC
 	bit  6,a
 	jp   nz,DebugFightFunc5D3A
 	bit  7,a
 	jp   nz,DebugFightFunc5D63
 	jr   DebugFightFunc5CD5
DebugFightFunc5D01:
	inc  c
	ld   a,c
	cp   a,$65
	jr   c,DebugFightFunc5D0A
	ld   a,$01
	ld   c,a
DebugFightFunc5D0A:
	ld   a,(wCurPartyMon)
	push de
	ld   de,wOTPartySpecies
	add  e
	ld   e,a
	jr   nc,DebugFightFunc5D16
	inc  d
DebugFightFunc5D16:
	ld   a,c
	ld   (de),a
	push bc
	push hl
	ld   bc,$000B
	add  hl,bc
	ld   bc,$8103
	call PrintNumber
	pop  hl
	pop  bc
	pop  de
	jp   DebugFightFunc5CD5
DebugFightFunc5D2A:
	dec  c
	ld   a,c
	cp   a,$65
	jr   nc,DebugFightFunc5D34
	and  a
	jp   nz,DebugFightFunc5D0A
DebugFightFunc5D34:
	ld   a,$64
	ld   c,a
	jp   DebugFightFunc5D0A
DebugFightFunc5D3A:
	ld   a,(wCurPartyMon)
	dec  a
	cp   a,$FF
	jp   z,DebugFightFunc5CD5
	ld   (wCurPartyMon),a
	dec  de
	push hl
	ld   bc,$000A
	add  hl,bc
	ld   a,$7F
	ld   (hl),a
	pop  hl
	ld   bc,hSerialReceive
	add  hl,bc
	push hl
	ld   bc,$000A
	add  hl,bc
	ld   a,$ED
	ld   (hl),a
	call DebugFightFunc5D8C
	pop  hl
	jp   DebugFightFunc5CD5
DebugFightFunc5D63:
	ld   a,(wCurPartyMon)
	inc  a
	cp   a,$06
	jp   nc,DebugFightFunc5CD5
	ld   (wCurPartyMon),a
	inc  de
	push hl
	ld   bc,$000A
	add  hl,bc
	ld   a,7F
	ld   (hl),a
	pop  hl
	ld   bc,$0028
	add  hl,bc
	push hl
	ld   bc,$000A
	add  hl,bc
	ld   a,$ED
	ld   (hl),a
	call DebugFightFunc5D8C
	pop  hl
	jp   DebugFightFunc5CD5
DebugFightFunc5D8C:
	ld   hl,wPartySpecies
	ld   a,(wCurPartyMon)
	add  l
	ld   l,a
	jr   nc,DebugFightFunc5D97
	inc  h
DebugFightFunc5D97:
	ld   a,(hl)
	ld   b,a
	ld   hl,wOTPartySpecies
	ld   a,(wCurPartyMon)
	add  l
	ld   l,a
	jr   nc,DebugFightFunc5DA4
	inc  h
DebugFightFunc5DA4:
	ld   a,(hl)
	ld   c,a
	ret
DebugFightFunc5DA7:
	ld   hl,wPartyCount
	ld   de,wOTPartyCount
	xor  a
	ld   (hl),a
	inc  hl
	ldi  a,(hl)
	ld   b,a
	ld   c,$06
	xor  a
	ld   (wBattleMode),a
DebugFightFunc5DB8:
	ld   a,b
	ld   (wCurPartySpecies),a
	ld   a,(hl)
	ld   b,a
	inc  de
	ld   a,(de)
	and  a
	jr   z,DebugFightFunc5DDB
	ld   (wCurPartyLevel),a
	xor  a
	ld   (wMonType),a
	ld   a,(wCurPartySpecies)
	and  a
	jr   z,DebugFightFunc5DDB
	push hl
	push de
	push bc
	ld   a,$10
	call Predef
	pop  bc
	pop  de
	pop  hl
DebugFightFunc5DDB:
	inc  hl
	dec  c
	jr   nz,DebugFightFunc5DB8
	ld   b,$07
	ld   hl,wPartySpecies
	ld   de,wOTPartyCount
DebugFightFunc5DE7:
	inc  de
	dec  b
	jp   z,DebugFightFunctionfdb66
	ldi  a,(hl)
	and  a
	jr   z,DebugFightFunc5DE7
	ld   a,(de)
	and  a
	jr   z,DebugFightFunc5DE7
	ld   hl,w_C2DC
	ld   b,$0F
	ld   c,$14
	call ClearBox
	ld   hl,w_C2DC
	ld   b,$0F
	ld   c,$14
	call ClearBox
	ld   hl,w_C2DC
	ld   b,$0F
	ld   c,$14
	call ClearBox
	ld   c,$14
	call DelayFrames
	ld   a,$01
	ld   (wBattleMode),a
	ld   de,DebugFightFunc61F9
	ld   a,(w_D900)
	cp   a,$65
	jr   c,DebugFightFunc5E2E
	ld   a,$02
	ld   (wBattleMode),a
	ld   de,DebugFightFunc6203
DebugFightFunc5E2E:
	ld   hl,w_C2F1
	call PlaceString
	ld   hl,w_C319
	ld   de,DebugFightFunc620D
	call PlaceString
	ld   a,(wEnemyMon)
	ld   b,a
	ld   a,(wBattleMode)
	dec  a
	jr   z,DebugFightFunc5E78
	ld   a,(wBattleMonStructEnd)
	ld   (wNamedObjectIndexBuffer),a
	ld   b,a
	ld   de,wNamedObjectIndexBuffer
	ld   hl,DebugFightFuncC341
	push bc
	ld   bc,$8103
	call PrintNumber
	ld   hl,DebugFightFuncC345
	ld   de,DebugFightFunc6233
	call PlaceString
	ld   hl,DebugFightFunc4B78
	ld   a,0E
	call FarCall_hl
	ld   hl,DebugFightFuncC345
	ld   de,wOTClassName
	call PlaceString
	pop  bc
	jr   DebugFightFunc5E9D
DebugFightFunc5E78:
	ld   a,b
	and  a
	jr   z,DebugFightFunc5E9D
	ld   de,wNamedObjectIndexBuffer
	ld   (de),a
	ld   hl,DebugFightFuncC341
	push bc
	ld   bc,$8103
	call PrintNumber
	ld   hl,DebugFightFuncC345
	ld   de,DebugFightFunc6233
	call PlaceString
	call GetPokemonName
	ld   hl,DebugFightFuncC345
	call PlaceString
	pop  bc
DebugFightFunc5E9D:
	ld   a,(wEnemyMonLevel)
	ld   c,a
	ld   de,wNamedObjectIndexBuffer
	ld   (de),a
	ld   hl,w_C350
	push bc
	ld   bc,$8103
	call PrintNumber
	pop  bc
DebugFightFunc5EB0:
	ld   a,$7F
	ld   (w_C340),a
	ld   (w_C34F),a
	ld   a,$ED
	ld   (w_C2F0),a
DebugFightFunc5EBD:
	push bc
	call DelayFrame
	call GetJoypadDebounced
	pop  bc
	ld   a,(ff00+hJoySum)
	bit  0,a
	jp   nz,DebugFightFunc5ED8
	bit  3,a
	jp   nz,DebugFightFunc6056
	bit  7,a
	jp   nz,DebugFightFunc5F1F
	jr   DebugFightFunc5EBD
DebugFightFunc5ED8:
	ld   hl,DebugFightFuncC341
	ld   de,DebugFightFunc6220
	call PlaceString
	ld   hl,w_C331
	ld   de,DebugFightFunc6233
	call PlaceString
	xor  a
	ld   b,a
	ld   c,a
	ld   a,(wBattleMode)
	dec  a
	jr   nz,DebugFightFunc5F09
	ld   a,$02
	ld   (wBattleMode),a
	ld   a,$7F
	ld   (w_C2E0),a
	ld   hl,w_C2F1
	ld   de,DebugFightFunc6203
	call PlaceString
	jp   DebugFightFunc5EBD
DebugFightFunc5F09:
	ld   a,$01
	ld   (wBattleMode),a
	ld   a,$7F
	ld   (C2DD),a
	ld   hl,w_C2F1
	ld   de,DebugFightFunc61F9
	call PlaceString
	jp   DebugFightFunc5EBD
DebugFightFunc5F1F:
	ld   a,$ED
 	ld   (w_C340),a
 	ld   a,$7F
 	ld   (w_C34F),a
 	ld   (w_C2F0),a
DebugFightFunc5F2C:
	push bc
	call DelayFrame
	call GetJoypadDebounced
	pop  bc
	ld   a,(ff00+hJoySum)
	bit  0,a
	jp   nz,DebugFightFunc5F51
	bit  1,a
	jp   nz,DebugFightFunc5FC5
	bit  3,a
	jp   nz,DebugFightFunc6056
	bit  4,a
	jp   nz,DebugFightFunc5FFD
	bit  6,a
	jp   nz,DebugFightFunc5EB0
	jr   DebugFightFunc5F2C
DebugFightFunc5F51:
	push bc
	ld   hl,w_C331
	ld   de,DebugFightFunc6233
	call PlaceString
	ld   hl,DebugFightFuncC345
	ld   de,DebugFightFunc6233
	call PlaceString
	pop  bc
	ld   a,(wBattleMode)
	dec  a
	jr   z,DebugFightFunc5F9F
	inc  b
	ld   a,b
	cp   a,$3E
	jr   c,DebugFightFunc5F73
	ld   b,$01
DebugFightFunc5F73:
	ld   a,b
	ld   (wNamedObjectIndexBuffer),a
	ld   de,wNamedObjectIndexBuffer
	ld   hl,DebugFightFuncC341
	push bc
	ld   bc,$8103
	call PrintNumber
	ld   a,(wNamedObjectIndexBuffer)
	ld   (wBattleMonStructEnd),a
	ld   hl,DebugFightFunc4B78
	ld   a,$0E
	call FarCall_hl
	ld   hl,DebugFightFuncC345
	ld   de,wOTClassName
	call PlaceString
	pop  bc
	jp   DebugFightFunc5F2C
DebugFightFunc5F9F:
	inc  b
	ld   a,b
	cp   a,$FE
	jr   c,DebugFightFunc5FA7
	ld   b,01
DebugFightFunc5FA7:
	ld   a,b
	ld   (wNamedObjectIndexBuffer),a
	ld   de,wNamedObjectIndexBuffer
	ld   hl,DebugFightFuncC341
	push bc
	ld   bc,$8103
	call PrintNumber
	call GetPokemonName
	ld   hl,DebugFightFuncC345
	call PlaceString
	pop  bc
	jp   DebugFightFunc5F2C
DebugFightFunc5FC5:
	push bc
	ld   hl,w_C331
	ld   de,DebugFightFunc6233
	call PlaceString
	ld   hl,DebugFightFuncC345
	ld   de,DebugFightFunc6233
	call PlaceString
	pop  bc
	ld   a,(wBattleMode)
	dec  a
	jr   z,DebugFightFunc5FEE
	dec  b
	ld   a,b
	cp   a,$3E
	jr   nc,DebugFightFunc5FE9
	and  a
	jp   nz,DebugFightFunc5F73
DebugFightFunc5FE9:
	ld   b,$3D
	jp   DebugFightFunc5F73
DebugFightFunc5FEE:
	dec  b
	ld   a,b
	cp   a,$FE
	jr   nc,DebugFightFunc5FF8
	and  a
	jp   nz,DebugFightFunc5FA7
DebugFightFunc5FF8:
	ld   b,$FD
	jp   DebugFightFunc5FA7
DebugFightFunc5FFD:
	ld   a,$7F
	ld   (w_C340),a
	ld   a,$ED
	ld   (w_C34F),a
DebugFightFunc6007:
	push bc
	call DelayFrame
	call GetJoypadDebounced
	pop  bc
	ld   a,($ff00+hJoySum)
	bit  0,a
	jp   nz,DebugFightFunc602C
	bit  1,a
	jp   nz,DebugFightFunc6047
	bit  3,a
	jp   nz,DebugFightFunc6056
	bit  5,a
	jp   nz,DebugFightFunc5F1F
	bit  6,a
	jp   nz,DebugFightFunc5EB0
	jr   DebugFightFunc6007
DebugFightFunc602C:
	inc  c
	ld   a,c
	cp   a,$65
	jr   c,DebugFightFunc6034
	ld   c,$01
DebugFightFunc6034:
	ld   hl,w_C350
	ld   a,c
	ld   de,wCurPartyLevel
	ld   (de),a
	push bc
	ld   bc,$8103
	call PrintNumber
	pop  bc
	jp   DebugFightFunc6007
DebugFightFunc6047:
	dec  c
	ld   a,c
	cp   a,$65
	jr   nc,DebugFightFunc6051
	and  a
	jp   nz,DebugFightFunc6034
DebugFightFunc6051:
	ld   c,$64
	jp   DebugFightFunc6034
DebugFightFunc6056:
	ld   a,b
	and  a
	jp   z,DebugFightFunc5EB0
	ld   a,c
	and  a
	jp   z,DebugFightFunc5EB0
	ld   a,(wBattleMode)
	dec  a
	jr   z,DebugFightFunc6070
	ld   a,b
	ld   (wOtherTrainerClass),a
	ld   a,c
	ld   (wOtherTrainerID),a
	jr   DebugFightFunc6078
DebugFightFunc6070:
	ld   a,c
	ld   (wCurPartyLevel),a
	ld   a,b
	ld   (wTempWildMonSpecies),a
DebugFightFunc6078:
	call SetPalettes
	ld   a,$80
	ld   (wBadges),a
	ld   hl,DebugFightFunc623E
	ld   de,wGameData
	ld   bc,$0006
	call CopyBytes
	ld   a,$25
	call Predef
	ld   a,$01
	ld   ($ff00+hBGMapMode),a
	xor  a
	ld   (wNumFleeAttempts),a
	ld   hl,wAttackMissed
	ld   bc,$0005
	call ByteFill
	ld   hl,wPlayerSubStatus5
	ld   bc,$0005
	call ByteFill
	call LoadFont
	call LoadFontsBattleExtra
	call ClearTileMap
	call ClearSprites
	ld   a,E4
	ld   ($ff00+47),a 	 ;bg pal
	ld   ($ff00+48),a 	 ;obj pal
	ld   ($ff00+49),a 	 ;obj pal
	ld   hl,wShadowOAMEnd
	ld   b,$01
	ld   c,$12
	call DrawTextBox
	ld   hl,w_C2BA
	ld   de,DebugFightFunc6169
	call PlaceString
	ld   hl,w_C2F4
	ld   de,DebugFightFunc6172
	call PlaceString
	ld   hl,w_C319
	ld   de,DebugFightFunc6181
	call PlaceString
	ld   de,wPartyCount
	xor  a
	ld   (de),a
	ld   (wCurPartyMon),a
	inc  de
	ld   hl,w_C31C
	push de
	push hl
DebugFightFunc60F2:
	ld   a,(wCurPartyMon)
	ld   de,wPartySpecies
	add  e
	ld   e,a
	jr   nc,DebugFightFunc60FD
	inc  d
DebugFightFunc60FD:
	ld   a,(de)
	cp   a,$FF
	jp   z,DebugFightFunc6158
	ld   (wNamedObjectIndexBuffer),a
	push hl
	ld   bc,$8103
	call PrintNumber
	inc  hl
	ld   de,DebugFightFunc61ED
	call PlaceString
	call GetPokemonName
	call PlaceString
	pop  hl
	push hl
	ld   bc,$000B
	add  hl,bc
	push hl
	ld   a,(wCurPartyMon)
	ld   hl,wPartyMon1Level
	ld   bc,$0030
	call AddNTimes
	ld   d,h
	ld   e,l
	ld   a,(de)
	ld   (wCurPartyLevel),a
	pop  hl
	ld   bc,$8103
	call PrintNumber
	ld   a,(wCurPartyMon)
	ld   de,wOTPartySpecies
	add  e
	ld   e,a
	jr   nc,DebugFightFunc6145
	inc  d
DebugFightFunc6145:
	ld   a,(wCurPartyLevel)
	ld   (de),a
	pop  hl
	ld   a,(wCurPartyMon)
	inc  a
	ld   (wCurPartyMon),a
	ld   bc,$0028
	add  hl,bc
	jp   DebugFightFunc60F2
DebugFightFunc6158:
	pop  hl
	pop  de
	ld   a,(wPartyMon1)
	ld   b,a
	ld   a,(wPartyMon1Level)
	ld   c,a
	xor  a
	ld   (wCurPartyMon),a
	jp   DebugFightFunc5BDC
DebugFightFunc6169:	;	data likely starts here. turn it back into hex.
	sub  d
	adc  h
	sub  e
	ld   a,a
	sbc  e
	jp   hl
	add  c
	sub  e
	ld   d,b
DebugFightFunc6172:
	ld   (hl),h
	ld   a,($ff00+c)
	ld   a,a
	ld   a,a
	push bc
	rst  08
	or   h
	ld   a,a
	ld   a,a
	ld   a,a
	ld   a,a
	and  a
	dec  a
	and  (hl)
	ld   d,b
DebugFightFunc6181:
	rst  30
	ld   a,(ff00+c)
	undefined opcode
	or   a,F6
	or   a,7F
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	ld   a,a
	ld   a,a
	or   a,F6
	or   a,4E
	ld   hl,sp-0E
	ld   a,a
	or   a,F6
	or   a,7F
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	ld   a,a
	ld   a,a
	or   a,F6
	or   a,4E
	ld   sp,hl
	ld   a,(ff00+c)
	ld   a,a
	or   a,F6
	or   a,7F
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	ld   a,a
	ld   a,a
	or   a,F6
	or   a,4E
	ld   a,(7FF2)
	or   a,F6
	or   a,7F
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	ld   a,a
	ld   a,a
	or   a,F6
	or   a,4E
	ei
	ld   a,(ff00+c)
	ld   a,a
	or   a,F6
	or   a,7F
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	ld   a,a
	ld   a,a
	or   a,F6
	or   a,4E
	undefined opcode
	ld   a,(ff00+c)
	ld   a,a
	or   a,F6
	or   a,7F
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	ld   a,a
	ld   a,a
	or   a,F6
	or   a,50
DebugFightFunc61ED:
	ld   a,a
	ld   a,a
	ld   a,a
	ld   a,a
	ld   a,a
	ld   d,b
DebugFightFunc61F3:
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	ld   d,b
DebugFightFunc61F9:
	xor  c
	add  c
	and  (hl)
	inc  de
	and  c
	xor  e
	adc  h
	adc  a
	undefined opcode
	ld   d,b
DebugFightFunc6203:
	ld   (de),a
	or   b
	undefined opcode
	and  l
	undefined opcode
	ld   a,a
	ld   a,a
	ld   a,a
	ld   a,a
	ld   d,b
DebugFightFunc620D:
	ld   (hl),h
	ld   a,(ff00+c)
	ld   a,a
	ld   a,a
	push bc
	rst  08
	or   h
	ld   a,a
	ld   a,a
	ld   a,a
	ld   a,a
	ld   a,a
	ld   a,a
	ld   a,a
	ld   a,a
	and  a
	dec  a
	and  (hl)
	ld   c,(hl)
DebugFightFunc6220:
	or   a,F6
	or   a,7F
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	undefined opcode
	ld   a,a
	or   a,F6
	or   a,50
DebugFightFunc6233:
	ld   a,a
	ld   a,a
	ld   a,a
	ld   a,a
	ld   a,a
	ld   a,a
	ld   a,a
	ld   a,a
	ld   a,a
	ld   a,a
	ld   d,b
DebugFightFunc623E:
	add  hl,bc
	undefined opcode
	and  (hl)
	inc  de
	ld   d,b
	ld   d,b
	inc  bc
	ld   h,e
	inc  b
	ld   h,e
	dec  bc
	ld   h,e
	<corrupted stop>
	ld   de,1263
	ld   h,e
	inc  de
	ld   h,e
	inc  d
	ld   h,e
	rst  38
endc